In [4]:
a=10.5
print(a)
type(a)


10.5


float

In [7]:
name='anu'
name

'anu'

In [2]:
print(a)

10.5


In [ ]:
_a=5

In [ ]:
Age=56
AGE=56
age=56
#3 of them are differernt.

In [5]:
print("welcome")

welcome


In [1]:
a=45
b=25
print(a+b)
sum=a+b
sum

70


70

In [17]:
# for taking values from user
a=int(input())
b=int(input())
a+b

12

In [21]:
#sum of 3 numbers
a=int(input())
b=int(input())
c=int(input())
a+b+c

16

In [8]:
a[5]

TypeError: 'int' object is not subscriptable

In [5]:
#multiplication of 2 numbers
a=int(input())
b=int(input())
a*b

6

In [25]:
#List
a=[2,4.5,'fidha',[3,4,5],8]
a

[2, 4.5, 'fidha', [3, 4, 5], 8]

In [38]:
li=[2,4,5,[56,63,2,2,8],5,5,1,2]
li

[2, 4, 5, [56, 63, 2, 2, 8], 5, 5, 1, 2]

In [40]:
#indexing(calling the values by addres)
li[-3]

5

In [41]:
li[3][1]

63

In [44]:
#taking the values from ' a number upto a number'(by position)
li[4:-2]

[5, 5]

In [17]:
# append
data=[4,6,8,44,7]
data

[4, 6, 8, 44, 7]

In [18]:
data.append(100)
data

[4, 6, 8, 44, 7, 100]

In [19]:
data.extend([66,77,3])

In [20]:
data

[4, 6, 8, 44, 7, 100, 66, 77, 3]

In [21]:
#to see the length of the data
len(data)

9

In [22]:
data.sort()

In [39]:
data

[3, 1, '1', 4, 6, 7, 8, 44, 66, 77, 100]

In [36]:
data.insert(1,1)

In [38]:
data

[3, 1, '1', 4, 6, 7, 8, 44, 66, 77, 100]

In [43]:
#how many times we are runnimg this,that many times 15 will be excecuted
data.insert(6,15)

In [44]:
data


[3, 1, '1', 4, 6, 7, 15, 15, 15, 8, 44, 66, 77, 100]

In [45]:
data.reverse()
data

[100, 77, 66, 44, 8, 15, 15, 15, 7, 6, 4, '1', 1, 3]

In [47]:
data.pop(1)
data

[100, 44, 8, 15, 15, 15, 7, 6, 4, '1', 1, 3]

In [49]:
data.count(15)

3

In [50]:
data.copy()
data

[100, 44, 8, 15, 15, 15, 7, 6, 4, '1', 1, 3]

In [51]:
data.insert(1,1)
data

[100, 1, 44, 8, 15, 15, 15, 7, 6, 4, '1', 1, 3]

In [54]:
#assigning value to the variable of first position
data[0]=50

In [55]:
data

[50, 1, 44, 8, 15, 15, 15, 7, 6, 4, '1', 1, 3]

In [57]:
#Tuple
a=(4,5.6,'sg')

In [59]:
#indexing in tuple
b=(2,5,6,4,2,2,9)
b[3]

4

In [60]:
b.count(2)


3

In [63]:
#for finding the index of the variable
b.index(5)

1

In [65]:
b.index(2)

0

In [91]:
#Set

s={5,7,2,2,6,6,8}
for i in s:
    print(i)

2
5
6
7
8


In [88]:
#changing or ordering a list by converting it into set and then into list
l=[2,3,4,5,5,5]
s=set(l)
s=list(s)


[2, 3, 4, 5]

In [99]:
a={2,3,4,5,5,5}
b={4,4,2,6,6,8,9}
print(a,b)


{2, 3, 4, 5} {2, 4, 6, 8, 9}


In [94]:
a.union(b)

{2, 3, 4, 5, 6, 8, 9}

In [95]:
a.intersection(b)

{2, 4}

In [96]:
a.difference(b)

{3, 5}

In [97]:
b.difference(a)

{6, 8, 9}

In [69]:
#for adding a value into a set
a.add(6)

In [100]:
a

{2, 3, 4, 5}

In [74]:
a.add(1)
a


{1, 2, 3, 4, 5, 6, 9}

In [77]:
b.copy
b

{2, 4, 6, 8, 9}

In [83]:
b.copy()
b

{2, 4, 6, 8, 9}

In [85]:
b.clear()
b

set()

In [86]:
a.pop()
a

{2, 3, 4, 5, 6, 9}

In [101]:
a.pop()
a

{3, 4, 5}

In [90]:
a.remove(5)
a

{4, 6, 9}

In [102]:
a.clear()

In [92]:
del a

In [103]:
a

set()

In [105]:
#dictionary
d={'name':'fidha','age':18,'mark':45}
d

{'name': 'fidha', 'age': 18, 'mark': 45}

In [106]:
d.items()

dict_items([('name', 'fidha'), ('age', 18), ('mark', 45)])

In [107]:
d.keys()

dict_keys(['name', 'age', 'mark'])

In [108]:
d.values()

dict_values(['fidha', 18, 45])

In [109]:
d['name']='roshan'
d

{'name': 'roshan', 'age': 18, 'mark': 45}

In [110]:
d.update()
d

{'name': 'roshan', 'age': 18, 'mark': 45}

In [111]:
d.pop('name')
d

{'age': 18, 'mark': 45}

In [112]:
co=d.copy()
co

{'age': 18, 'mark': 45}

In [113]:
d.clear()
d

{}

In [114]:
#string
s="how' you"
len(s)

8

In [115]:
s[-5]

"'"

In [116]:
s=s.upper()
s

"HOW' YOU"

In [117]:
s.lower()

"how' you"

In [118]:
# previously,we only command to make it lower,but in above,we assign it into upper.so the s will be in upper
s

"HOW' YOU"

In [119]:
#to check whether it is in upper or not
s.isupper()



True

In [122]:
#to check whether it is in lower or not
s.islower()



False

In [128]:
s.capitalize()


"How' you"

In [164]:
s

"HOW' YOU"

In [171]:
#to check whether it is starting with that ....
s.startswith('HO')

True

In [169]:
#to check whether it is ending with that ....
s.endswith("' YOU")

True

In [130]:
s='helloworld'
s

'helloworld'

In [131]:
s

'helloworld'

In [132]:
#to count the number of l
s.count('l')


3

In [182]:
#it will give the position of first l
s.find('l')

2

In [133]:
#position of that letter
s.index('e')

1

In [139]:
s.isalnum()

True

In [136]:
s.isalpha()


True

In [138]:
s

'helloworld'

In [142]:
s='hello world'
s

'hello world'

In [143]:
s.isalpha()

False

In [144]:
s.split()

['hello', 'world']

In [145]:
s='123'

In [146]:
s.isnumeric()

True

In [147]:
s='hello12'
s

'hello12'

In [148]:
s.isnumeric()

False

In [149]:
s.isalnum()

True

In [152]:
s='123'
s

'123'

In [153]:
s.isnumeric


<function str.isnumeric()>

In [154]:
s='hello12'
s

'hello12'

In [155]:
s.isnumeric()


False

In [ ]:
#opertors

# arithmatic
# logical
# bitwise
# identity
# assignment
# comparison
# membership

In [214]:
65//10

6

In [216]:
4%2==0

False

In [ ]:
in
not in


In [ ]:
#condition statements
#if
#if else
#elif
#nestedif

In [222]:
mark=35
if mark>=40:
    print('A+')
elif mark >=35 and mark<40:
    print('B+')
elif mark>=30 and  mark<35:
    print('C+')
else:
    print('Fail')

B+


In [156]:
num=10
if num>8:
    if num>9 and num<15: #nested if
        print('yes')
else:
    print('not')

yes


In [230]:
mark=int(input())
if mark>=90 and mark<100:
 print('A+')
elif mark>=80 and mark<90:
 print('A')
elif mark>=70 and mark<80:
 print('B+')
if  mark>=60 and mark<70:
 print('B')
if mark<50:
 print('fail')





A+


In [232]:
#looping statements
# 1.for loop
# for iterationvariable in sequencetype:
#     stmts

In [241]:
l=[1,2,5,3,55,34,2]
# for i in range(2,21,3):
#     print(i)
for i in l:
    if i%2!=0:
        print(i,'odd')
    else:
        print(i,'even')
        

1 odd
2 even
5 odd
3 odd
55 odd
34 even
2 even


In [247]:
#while
i=1
while i<10:
    if i%2!=0:
        print(i,'odd')
    else:
        print(i,'even')   
    i+=1

1 odd
2 even
3 odd
4 even
5 odd
6 even
7 odd
8 even
9 odd


In [1]:
s='hello' world'
s

'hello world'

In [3]:
d=s.capitalize()
d

'Hello world'

In [1]:
i=0
while i<=10:
    if i==6:
        break
    print(i)
    i=i+1
    



0
1
2
3
4
5


In [12]:
i=0
while i<10:
    i=i+1
    if i==6:
    
      continue
    print(i)
   

1
2
3
4
5
7
8
9
10


In [2]:
#multiplication table
a=int(input('enter a number'))
b=int(input("limit"))
for i in range(1,b+1):#range(lower limit,upper limit+1,step value).here there is no step value.
    c=a*i
    print(f'{a}*{i}={c}')#f stands for format.

5*1=5
5*2=10
5*3=15
5*4=20
5*5=25


In [22]:
#functions.
#def is a keyword to call functions.
def message():#here message is the name we had given to the function.
    print('hi')
message() #calling a function   

hi


In [3]:
def message(name):
    print('hi '+name)#adding name with hi.
message('fidha') 

hi fidha


In [25]:
#function for sum of two numbers.
def sum(a,b):
    print(a+b)
sum(10,20)   

30


In [26]:
#function for square of a number.
def square(a):
    print(a*a)
square(5)    

25


In [32]:
#function for multiplication table
def multiplication(a,b):
    for i in range(1,b+1):
     print(f'{a}*{i}={a*i}')

multiplication(5,10)    

5*1=5
5*2=10
5*3=15
5*4=20
5*5=25
5*6=30
5*7=35
5*8=40
5*9=45
5*10=50


In [35]:
#function for multiplication table by taking values from the user
def multiplication(a,b):
    for i in range(1,b+1):
     print(f'{a}*{i}={a*i}')
a=int(input('enter a number'))
b=int(input('enter the limit'))
multiplication(a,b)  #function calling

5*1=5
5*2=10
5*3=15
5*4=20
5*5=25
5*6=30


In [3]:
#function for fibonacci series
def fibonacci(limit):
    a,b=0,1
    while a<=limit:
        print(a)
        a,b=b,a+b
        
# limit=int(input('enter a limit'))
fibonacci(5)        


0
1
1
2
3
5


In [6]:
#pallindrome function
#malayalam
# fidha
# ahdif
def pallindrome(a):
  return a==a[::-1] #for checking reverse of the string.it is better to use return here otherwise if condition will make confuions.
a=(input('enter the word'))

                                    
if pallindrome(a):
    print('pallindrome')
else :
    print('not pallindrome ') 
  



pallindrome


In [5]:
def palindrome(input_string):
  return input_string==input_string[::-1]
palindrome('malayalam')


True

In [63]:
li=[6,42,5,8,4,6,2,1,7,6]
b=min(li)
b


1

In [61]:
a={2,3,5,4,7,9}
b=max(a)
print(b)






9


In [65]:
li=(6,42,5,8,4,6,2,1,7,6)
b=min(li)
b


1

In [68]:
li=-22
b=abs(li)#for finding the absolute value. 
b


22

In [69]:
#lambda function
#we can pass so many arg,but only one expression
#it is anonymous function
add=lambda x,y:x+y # function = lambda parameters:operation
add(2,9)

11

In [79]:
#recursive function(a function inside a function)
#factorial
def factorial(n):
    if n==0 or n==1:
        return 1
    else :
        return n *factorial(n-1)
factorial(3)


    

6

In [ ]:
#major concepts of oops
#class
#objects
#data abstraction
#encapsulation
#inheritance-single level,multiple,multi level,hierarchy.
#polymorphism

In [83]:
class Car:         #class name should always start with capital letter
    def __init__(self,color,price,model):#constructor
        self.color=color #connecting init with parameters
        self.price=price
        self.model=model
    def start(self):   #method
        print('engine started')    
car1=Car(color='black',price=50000,model=2020) #object outside the class
car2=Car(color='grey',price=60000,model=2022) 
car1.start()
print(car1.price)     

engine started
50000


In [86]:
class Person:
    def __init__(self,name,contact):
        self.name=name
        self.contact=contact
    def addrres(self):
        print('abc house,xyz nagar')
class Doctor(Person):#doctor is a child class of the parent class person.
    pass #data in parent class is inherited to child class
ob1=Doctor(name='raju',contact=123456852)   
print(ob1.name)  
ob1.addrres()

raju
abc house,xyz nagar


In [12]:
a=int(input('enter you age '))
if a>=25:
    print('You are eligible to vote .You are eligible to participate in the election')
elif a>=18:
    print('You are eligible to vote .You are not eligible to participate in election')
else:
    print("not eligible")

You are eligible to vote .You are eligible to participate in the election


In [2]:
import random
def generate_password(n):
    char='ANHUFYRDTEDYUHB'
    password=''

    for i in range(n):
        password=password+random.choice(char)
    return password
limit=int(input('enter length'))
password=generate_password(limit)
print(password)   

YNBH


# Numpy

In [7]:
pip install numpy

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------------- -------------------------- 20.5/61.0 kB ? eta -:--:--
     ------------- -------------------------- 20.5/61.0 kB ? eta -:--:--
     -------------------------------------- 61.0/61.0 kB 546.2 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.8 MB 2.6 MB/s eta 0:00:06
    --------------------------------------- 0.2/15.8 MB 2.9 MB/s eta 0:00:06
   - -------------------------------------- 0.5/15.8 MB 3.1 MB/s eta 0:00:05
   - -------------------------------------- 0.8/15.8 MB 4.5 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/15.8 MB 4.5 MB/s eta 0:00:04
   --- ------------------------------------ 1.3/15.8 MB 4.7 MB/s eta 0:00:04
   --- ------------------------------------ 1.6/15.8 MB 5.0 MB/s eta 0:00:03
   ---- -------------

In [29]:
import numpy as np
a=np.array([1,2,3,3,4,6,4,6,7,9])
a[2]

3

In [24]:
a.ndim #numpy array dimension

1

In [28]:
a=np.array([[1,2,3],[3,3,4]])
a

array([[1, 2, 3],
       [3, 3, 4]])

In [30]:
a=np.array([[1,2]])
a[0][1]


2

In [33]:
#numpy indexing
a=np.array([[1,2],[3,5],[5,6]])
a[1][-1]

5

In [37]:
a=np.array([2,4,5,3])
a[2:4] #numpy slicing

array([5, 3])

In [40]:
a=np.array([[9,6,3],[3,8,7],[5,4,6],[2,4,5]])
a

array([[9, 6, 3],
       [3, 8, 7],
       [5, 4, 6],
       [2, 4, 5]])

In [41]:
a=np.array([[9,6,3],[3,8,7],[5,4,6],[2,4,5]])
print(a[1])
print(a[2])

[3 8 7]
[5 4 6]


In [44]:
#numpy slicing
a=np.array([[9,6,3],[3,8,7],[5,4,6],[2,4,5]])
a[1:3]

array([[3, 8, 7],
       [5, 4, 6]])

In [46]:
np.zeros((5,6),int) #(size of array,data type)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [47]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
np.full((6,7),4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [51]:
np.arange(1,11,2) #to create an array and print data from a specific value upto specific value.

array([1, 3, 5, 7, 9])

In [53]:
np.linspace(2,50,5) #to print specific values between some value and its equally divided into (step value)values 

array([ 2., 14., 26., 38., 50.])

In [60]:
np.random.random(50)

array([0.09869007, 0.51085654, 0.47415831, 0.21685776, 0.34449791,
       0.39862316, 0.39708347, 0.18404049, 0.091549  , 0.95544149,
       0.76894653, 0.81235596, 0.1207447 , 0.80593869, 0.1499691 ,
       0.41600725, 0.76766006, 0.61832798, 0.34546237, 0.12877713,
       0.0303866 , 0.22567808, 0.89598695, 0.08926702, 0.63725777,
       0.41937032, 0.34247308, 0.13389226, 0.50992806, 0.33262006,
       0.99411874, 0.07470549, 0.08938424, 0.5380195 , 0.21440344,
       0.97826674, 0.74185839, 0.80962941, 0.28470801, 0.55740048,
       0.33722351, 0.4427081 , 0.68329392, 0.1881842 , 0.07249964,
       0.13133605, 0.26590672, 0.46985191, 0.3296818 , 0.39357004])

In [80]:
np.random.randint(1,15,5)
s=np.random.randint(1,15,(4,3))
s.shape

(4, 3)

In [84]:
a=np.array([2,3])
a.dtype
ss=a.astype('int64')
ss

array([2, 3], dtype=int64)

In [91]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
# print(a)
b=np.insert(a,2,5,axis=0)
c=np.insert(b,1,7,axis=1)
# print(b)
print(c)

[[1 7 2 3]
 [4 7 5 6]
 [5 7 5 5]
 [7 7 8 9]]


In [93]:
a=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
b=np.insert(a,3,6,axis=0)
c=np.insert(b,3,8,axis=1)
c

array([[1, 2, 3, 8, 4, 5],
       [1, 2, 3, 8, 4, 5],
       [1, 2, 3, 8, 4, 5],
       [6, 6, 6, 8, 6, 6],
       [1, 2, 3, 8, 4, 5]])

In [94]:
#create a(4,5)matrix and insert a row i 3rd position & insert a coloumn in 3rd position 
#delete the first coloumn,& 2nd row 
a=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
b=np.insert(a,3,6,axis=0)
c=np.insert(b,3,8,axis=1)
d=np.delete(c,0,axis=1)
e=np.delete(d,1,axis=0)
e

array([[2, 3, 8, 4, 5],
       [2, 3, 8, 4, 5],
       [6, 6, 8, 6, 6],
       [2, 3, 8, 4, 5]])

In [118]:
a=np.array([1,2,3])
b=np.append(a,6)
b=b**3
b

array([  1,   8,  27, 216], dtype=int32)

In [110]:
#create a numpy array (4,3) with zeros & change the array values using indexing
a=np.zeros((4,3))
a[2][1]=3
a[0][0]=1
a[2:3]=(1,2,5)
a

array([[1., 0., 0.],
       [0., 0., 0.],
       [1., 2., 5.],
       [0., 0., 0.]])

In [124]:
arr=np.array([[4,5,7,8],[8,6,9,7],[2,5,4,9]])
arr1=np.array([[2,5,6,4],[5,9,7,6],[3,2,0,5]])
np.subtract(arr,arr1)
np.multiply(arr,arr1)
a=np.divide(arr,arr1)
a

C:\Users\ACER\AppData\Local\Temp\ipykernel_10192\1802888164.py:5: RuntimeWarning: divide by zero encountered in divide
  a=np.divide(arr,arr1)


array([[2.        , 1.        , 1.16666667, 2.        ],
       [1.6       , 0.66666667, 1.28571429, 1.16666667],
       [0.66666667, 2.5       ,        inf, 1.8       ]])

In [125]:
a=np.array([1,1,1,2,2,2,5,5,3,6,4,4,6,3,5])
b=np.unique(a)


array([1, 2, 3, 4, 5, 6])

In [132]:
a=np.array([1,1,1,2,2,2,5,5,3,6,4,4,6,3,5])
b=np.unique(a,return_counts=True) #for finding how many times the number repeated.
print(b)
c=np.unique(a,return_index=True) #for finding the addres of the  numbers
c



(array([1, 2, 3, 4, 5, 6]), array([3, 3, 2, 2, 3, 2], dtype=int64))


(array([1, 2, 3, 4, 5, 6]), array([ 0,  3,  8, 10,  6,  9], dtype=int64))

In [139]:
a=np.array([[1,2],[3,4]])
np.max (a)
b=np.min(a,axis=1)
b

array([1, 3])

In [141]:
a=np.array([[1,2],[3,4]])

b=np.max(a,axis=1)
print(b)
c=b=np.max(a,axis=0)
c

[2 4]


array([3, 4])

In [146]:
a=np.arange(2,10,3)
b=np.arange(2,10,3)
c=np.arange(2,10,3)
print(a)
print(b)
print(c)

[2 5 8]
[2 5 8]
[2 5 8]


In [149]:
#create a 3x3 matrix with values ranging from 2 to 10.
s=np.random.randint(1,10,(3,3))
s

array([[5, 3, 6],
       [6, 8, 4],
       [6, 5, 3]])

In [156]:

array = np.arange(1, 10).reshape(3, 3)
print(array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [159]:
#print unique elements from numpy.
a=np.array([4,5,6,8,2,2,3,6,5,6])
np.unique(a)

array([2, 3, 4, 5, 6, 8])

In [169]:
#create (2,3) array and find
#shape
#dimension
#print type
a=np.array([[1,2,3],[4,5,6]])
np.shape(a)
a.ndim
b=type(a)
b


numpy.ndarray

In [177]:
a=np.zeros((3,3),int)

a[0][0]=3
a[1][1]=8
a[2][2]=5
a

array([[3, 0, 0],
       [0, 8, 0],
       [0, 0, 5]])

In [178]:
np.diagflat([6,7,8]) 

array([[6, 0, 0],
       [0, 7, 0],
       [0, 0, 8]])

In [181]:
a=np.array([[1,2,3],[4,5,6],[9,8,7]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7]])

In [193]:
a[1::2]

array([[4, 5, 6]])

In [200]:
#checkerboard
a=np.zeros([5,5],int)
a[::2,::2]=1
a[1::2,1::2]=1
a

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [219]:
a=np.full((5,5),5)
a[1::,0:1]=4
a[1:2,1:4]=1
a[1:4,4:5]=2
a[4:5,1:5]=3
a[2:4,1:2]=0
a[3:4,2:4]=8
a[2:3,2:3]=10
a[2:3,3:4]=9
a

array([[ 5,  5,  5,  5,  5],
       [ 4,  1,  1,  1,  2],
       [ 4,  0, 10,  9,  2],
       [ 4,  0,  8,  8,  2],
       [ 4,  3,  3,  3,  3]])